name: Build and Push Docker Image (Linux only)

on:
  push:
    branches: [ dev ]
  workflow_dispatch:  # Allow manual trigger

env:
  IMAGE_NAME: silvinwillemsen/choras-frontend
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64  # Add linux/arm64 if you want multi-arch
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Show pushed images
        run: docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:${{ env.TAG }}
 